version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.1.4
    environment:
      TZ: "/usr/share/zoneinfo/Australia/Melbourne"
    steps:
      - checkout
      - run: sudo npm update -g
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:8.1.4
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:8.1.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "c6:13:c6:59:b8:18:32:6c:82:30:bb:0e:c2:5f:f6:15"
      - run: ./deploy.sh

workflows:
  version: 2
  build_test_deploy:
      jobs:
        - build
        - test:
            requires:
              - build
        - deploy:
            requires:
              - test